### ISSUE TITLE
What's your plan with the 1.1K pending pull requests?

### ISSUE THREAD

**Issue by 8ctopus** [LeTraceurSnork/WordPress-Security-Advisories#1299]

**Comment by LeTraceurSnork** [comment]
https://github.com/LeTraceurSnork/WordPress-Security-Advisories/pull/1300
Merged. Composer said that it installs properly, so no need of that obsoleted PRs, I'm closing them. As soon as I'm done, I'm turning renovator on again and waiting for brand new PRs (hopefully not 1.1k xD)

**Comment by 8ctopus** [comment]
Awesome!
